language: cpp
sudo: enabled
compiler:
  - gcc
dist: bionic

before_install:
# GLM: We can get this from the standard Ubuntu repository, any recent version will do
  - sudo apt-get install -y libglm-dev
# TRIMESH: Get dependencies from standard repos, and build project from git using makefile
  - sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libxi-dev
  - git clone https://github.com/Forceflow/trimesh2.git
  - cd trimesh2 && make && cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make