name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: | 
        sudo apt update
        sudo apt-get install -y libglm-dev
        sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libxi-dev
    - name: get and build trimesh
      run: |
        git clone https://github.com/Forceflow/trimesh2.git
        cd trimesh2 && make && cd ..
    - name: build ooc_svo_builder
      run: |
        mkdir build
        cd build
        cmake ..
        make
